### ISSUE TITLE
보상에 관한 유저 세이브데이터 추가

### ISSUE THREAD

**Issue by CGyB** [capstone-dku/word-game#6]
2차시에 작업내용 중 보상에 대한 부분을 저장할 유저데이터 추가.

**Comment by CGyB** [comment]
코인, 가지고 있는 아이템, 입장권 개수, 살수 있는 아이템 리스트 추가

**Comment by virtus2** [comment]
현재 추가할만한 데이터는 다 추가되었으니 이슈 닫겠습니다
다른 데이터가 더 필요하면 UserData 클래스의 멤버로 추가하면 될 듯 합니다
